### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ARTI1208** [JetBrains/skiko#740] opened 2023-07-01 09:17 UTC
Trying to use compose in KMM (kotlin 1.9-RC, 1.5.0-dev1080, skiko 0.7.63, also checked skiko 0.7.67), got error linking for IOS

```
Undefined symbols for architecture arm64:
  "_org_jetbrains_skia_TextBlobBuilderRunHandler__1nGetFinalizer", referenced from:
      _kfun:org.jetbrains.skia.shaper.TextBlobBuilderRunHandler._FinalizerHolder.$init_global#internal in result.o
  "_org_jetbrains_skia_TextBlobBuilderRunHandler__1nMake", referenced from:
      _kfun:org.jetbrains.skia.shaper.TextBlobBuilderRunHandler#<init>(org.jetbrains.skia.ManagedString?;kotlin.Boolean;kotlin.Float;kotlin.Float){} in result.o
  "_org_jetbrains_skia_TextBlobBuilderRunHandler__1nMakeBlob", referenced from:
      _objc2kotlin_kfun:org.jetbrains.skia.shaper.TextBlobBuilderRunHandler#makeBlob(){}org.jetbrains.skia.TextBlob? in result.o
  "_org_jetbrains_skia_svg_SVGCanvasKt__1nMake", referenced from:
      _kfun:org.jetbrains.skia.svg.SVGCanvas#make(org.jetbrains.skia.Rect;org.jetbrains.skia.WStream;kotlin.Boolean;kotlin.Boolean){}org.jetbrains.skia.Canvas in result.o
ld: symbol(s) not found for architecture arm64
```

I checked binaries and see that there are:
 _org_jetbrains_skia_svg_SVGCanvas__1nMake (not _org_jetbrains_skia_svg_SVGCanvas**Kt**__1nMake), 

_org_jetbrains_skia\_**shaper**_TextBlobBuilderRunHandler__1nGetFinalizer (not _org_jetbrains_skia_TextBlobBuilderRunHandler__1nGetFinalizer), 

_org_jetbrains_skia\_**shaper**_TextBlobBuilderRunHandler__1nMake (not _org_jetbrains_skia_TextBlobBuilderRunHandler__1nMake), 

_org_jetbrains_skia\_**shaper**_TextBlobBuilderRunHandler__1nMakeBlob (not _org_jetbrains_skia_TextBlobBuilderRunHandler__1nMakeBlob)

I guess @ExternalSymbolName values were not specified correctly / were not updated

**Comment by AlexeyTsvetkov** [comment] 2023-07-04 15:12
@ARTI1208 can you share an example project, where the issue is reproducible?

**Comment by ARTI1208** [comment] 2023-07-04 18:36
https://github.com/ARTI1208/SkikoLinkingErrorExample

Any of :shared:linkDebugFrameworkIosArm64, :shared:linkDebugFrameworkIosX64, :shared:linkDebugFrameworkIosSimulatorArm64 will fail

**Comment by AlexeyTsvetkov** [comment] 2023-07-16 22:07
@ARTI1208 your example works fine for me, if I comment out `transitiveExport = true` here https://github.com/ARTI1208/SkikoLinkingErrorExample/blob/main/shared/build.gradle.kts#L28

Do you actually need to export all APIs (including Compose and Skiko) to Objective-C and Swift?
Besides, exporting transitive dependencies makes linking much-much slower (on your example linking with exported dependencies takes 3x as much time).

**Comment by AlexeyTsvetkov** [comment] 2023-07-16 22:30
> I guess @ExternalSymbolName values were not specified correctly / were not updated

@ARTI1208 you're right about the external symbol names. We will fix that. With the correct values your project links even with `transitiveExport = true`.

**Comment by ARTI1208** [comment] 2023-07-17 12:23
> Do you actually need to export all APIs (including Compose and Skiko) to Objective-C and Swift? 

I'm not sure actually (not ios dev), but that's the way our project was configured for quite a long time. I'll investigate this at the end of the week, thanks for notice

**Comment by ARTI1208** [comment] 2023-07-17 12:24
> With the correct values your project links

Yeah, for quick check of compose for ios I ended up recompiling skiko with fixed values

**Comment by keshuraiib** [comment] 2023-12-20 11:22
Hello, i am facing the same issue when exported the KMM project to iOSArm64Main.Framework and trying to use this framework in my existing iOS project. 

Here is the error . Any solutions? 

```
ld: Undefined symbols:
  _org_jetbrains_skia_TextBlobBuilderRunHandler__1nGetFinalizer, referenced from:
      _kfun:org.jetbrains.skia.shaper.TextBlobBuilderRunHandler._FinalizerHolder#<init>(){} in ibshared[arm64][148](liborg.jetbrains.skiko:skiko-cache.a.o)
  _org_jetbrains_skia_TextBlobBuilderRunHandler__1nMake, referenced from:
      _kfun:org.jetbrains.skia.shaper.TextBlobBuilderRunHandler#<init>(org.jetbrains.skia.ManagedString?;kotlin.Boolean;kotlin.Float;kotlin.Float){} in ibshared[arm64][148](liborg.jetbrains.skiko:skiko-cache.a.o)
  _org_jetbrains_skia_TextBlobBuilderRunHandler__1nMakeBlob, referenced from:
      _kfun:org.jetbrains.skia.shaper.TextBlobBuilderRunHandler#makeBlob(){}org.jetbrains.skia.TextBlob? in ibshared[arm64][148](liborg.jetbrains.skiko:skiko-cache.a.o)
  _org_jetbrains_skia_svg_SVGCanvasKt__1nMake, referenced from:
      _kfun:org.jetbrains.skia.svg.SVGCanvas#make(org.jetbrains.skia.Rect;org.jetbrains.skia.WStream;kotlin.Boolean;kotlin.Boolean){}org.jetbrains.skia.Canvas in ibshared[arm64][148](liborg.jetbrains.skiko:skiko-cache.a.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by okushnikov** [comment] 2024-09-25 09:51
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-740">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-25 10:39 UTC
