### ISSUE TITLE
Mouse pointers moves jumpy when hovered over skiko window

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#558] opened 2022-07-22 11:19 UTC
Reproducible on: Fleet and JetBrains Toolbox 1.25.12569
Platform: Windows 11
Display refresh rate: 120Hz
Not reproducible on: IntelliJ IDEA Ultimate

So it looks like a problem with Skiko or maybe JBR17
But I have no idea how some user space code can affect os mouse pointer

https://user-images.githubusercontent.com/4352041/180426864-410d8260-670e-4866-8d20-331dcad25bf3.mp4

**Comment by igordmn** [comment] 2022-07-25 10:37
You mean laggy? :)

The issue is probably related to G-Sync. I don't know many details, but as far as I remember, it happens, if the user forcefully enable GSync in desktop mode in display settings (but I am not sure).

We tried to fix this issue, but unsuccessfully so far. It is a bug/feature of NVIDIA drivers. Even [Microsoft Terminal](https://github.com/microsoft/terminal/issues/649) had this issue (or still has). We found a very hacky way to fix that - show 1px  Swing Component above SkiaLayer. It seems when we use OpenGL (and Swing uses it if I am not mistaken), the screen switches to the continuous mode, not adaptive. But we haven't merged it, because we hadn't found a way to make the pixel transparent :D.

**Comment by igordmn** [comment] 2022-07-25 10:38
The issue in [Compose](https://github.com/JetBrains/compose-jb/issues/1648)

**Comment by roschlau** [comment] 2022-07-29 14:25
@igordmn I'm seeing this problem in Fleet and Toolbox even when G-SYNC is only enabled for full screen mode:
![image](https://user-images.githubusercontent.com/16798225/181781071-f377b19c-5a68-4cee-a644-a740c9083366.png)
I have to disable G-SYNC completely to get rid of the stutter/lagging.

**Comment by SergeevPavel** [comment] 2022-08-02 17:20
Same bug in Libre Office https://bugs.documentfoundation.org/show_bug.cgi?id=134631

**Comment by okushnikov** [comment] 2024-09-25 09:53
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-558">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-25 10:41 UTC
