### ISSUE TITLE
SkikoAndroidSample crashes with skiko v0.7.68

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/skiko#761] opened 2023-07-13 10:29 UTC
Just opened the `SkikoAndroidSample`, set the skiko version and ran it on Nexus 10 emulator.

Patch:
```
Index: samples/SkiaAndroidSample/gradle.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/samples/SkiaAndroidSample/gradle.properties b/samples/SkiaAndroidSample/gradle.properties
--- a/samples/SkiaAndroidSample/gradle.properties	(revision 39fb88f6a22bdd20f1cd82e3719b005885ca3648)
+++ b/samples/SkiaAndroidSample/gradle.properties	(date 1689243563827)
@@ -1,1 +1,2 @@
 # android.useAndroidX=true
+skiko.version=0.7.68
```  

Traceback:
```
FATAL EXCEPTION: main
Process: org.jetbrains.skiko.sample, PID: 30310
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN4sksg4NodeD2Ev" referenced by "/data/app/~~hx0DsiRO9IgmXXsuYjUCJg==/org.jetbrains.skiko.sample-MCoeO9133-3tnKrJOnzuag==/base.apk!/lib/arm64-v8a/libskiko-android-arm64.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:78)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at org.jetbrains.skia.paragraph.FontCollection.<clinit>(FontCollection.kt:11)
	at org.jetbrains.skiko.sample.Clocks.<init>(Clocks.kt:25)
	at org.jetbrains.skiko.sample.MainActivity.onCreate(MainActivity.kt:27)
	at android.app.Activity.performCreate(Activity.java:8051)
	at android.app.Activity.performCreate(Activity.java:8031)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by netherpyro** [comment] 2023-07-28 14:16
jfi Seems it started from 0.7.67
on 0.7.63 was fine

**Comment by Siedlerchr** [comment] 2023-08-08 10:50
Yep I get the same error with v0.7.75 as well under Android

**Comment by Siedlerchr** [comment] 2023-09-13 12:21
v 0.7.80 works again for me

**Comment by IKupriyanov-HORIS** [comment] 2023-09-20 11:20
v0.7.81 is broken. Same exception again.

**Comment by SanmerDev** [comment] 2023-11-10 03:58
v0.7.84 is broken.

**Comment by IKupriyanov-HORIS** [comment] 2023-12-04 11:29
v0.7.89 works fine

**Comment by IKupriyanov-HORIS** [comment] 2024-03-21 20:10
Ok, things getting worse. The latest version I managed to launch is `0.7.92`. 

How Skiko fails on Android:
| Version | Arch | Error |
|-----------|----|---------|
| 0.7.93 | aarch64 | cannot locate symbol "_ZN4sksg4NodeD2Ev" |
| 0.7.94 | aarch64 | cannot locate symbol "__aarch64_ldadd4_relax" |
| 0.7.95 | aarch64 | cannot locate symbol "__aarch64_ldadd4_relax" |
| 0.7.96 | aarch64 | cannot locate symbol "__aarch64_ldadd4_relax" |
| 0.7.97 | aarch64 | cannot locate symbol "_ZN4sksg4NodeD2Ev" |
| 0.7.98 | aarch64 | cannot locate symbol "__aarch64_ldadd4_relax" |
| 0.7.98.1 | aarch64 | cannot locate symbol "_ZN4sksg4NodeD2Ev" |

**Comment by michaellee123** [comment] 2024-04-16 17:12
0.8.0 has same crash info

**Comment by sbilsky** [comment] 2024-07-15 14:04
Checked on 0.8.10, still an issue, crashed with cannot locate symbol "__aarch64_ldadd4_relax"

**Comment by arashcoder** [comment] 2024-08-12 05:46
Hi! We were planning to use this framework in our KMM project, but this issue has prevented us from doing so. Are there any plans to fix it? Thanks!

**Comment by kexuejin** [comment] 2024-08-27 02:20
I tried many versions, and all versions after 0.7.93 will cause crashes. I suspect it's a problem with the CI compiled package, so I tried to compile from source code, and directly unzipped the generated jar package to replace the original so, and it worked fine! The attachment is the so I compiled successfully, which can be replaced directly. Remember to comment out the following code, otherwise it will be downloaded and replaced from maven again.

// skikoNativeX64(libs.skiko.android.runtime.x64)
// skikoNativeArm64(libs.skiko.android.runtime.arm64)

Of course, you can also try to compile it yourself, enter the skiko directory, and execute
../gradlew publishToBuildRepo -Pskiko.android.enabled=true

Then you can extract the jar package from build/repo and unzip it.
I hope the official can solve this problem!

[jniLibs.zip](https://github.com/user-attachments/files/16755581/jniLibs.zip)

**Comment by Siedlerchr** [comment] 2024-09-04 12:21
I can confirm that building locally (on macOS on an m1) works with agp 8.5.1, I could use it with mavenLocal as well.  
The CI builds on Ubuntu 20.04 https://github.com/JetBrains/skiko/blob/c479fc9b52497c2b33ff4b20612ad801178086e1/.github/workflows/ci.yml#L190 

It seems to be a problem with the NDK/agp and a specific clang version, at least this issue seems to be point somehow in the same direction
https://github.com/opencv/opencv/issues/24856

**Comment by igordmn** [comment] 2024-09-04 13:35
The Android publication is disabled until it is fixed.

The Android target was added as an experiment, so we don't have much resources to support published artifacts.

**Comment by igordmn** [comment] 2024-09-04 13:35
The publishing CI is private on TeamCity. It builds using [Docker container](https://github.com/JetBrains/skiko/tree/c479fc9b52497c2b33ff4b20612ad801178086e1/skiko/docker/linux-android-amd64).

and builds with this command:
```
./gradlew publishAndroidPublicationToComposeRepoRepository publishSkikoJvmRuntimeAndroidX64PublicationToComposeRepoRepository publishSkikoJvmRuntimeAndroidArm64PublicationToComposeRepoRepository --info --full-stacktrace -Pdeploy.version=0.0.0 -Pdeploy.release=true -Pskiko.android.enabled=true
```

If someone can reproduce it locally, using the docker above, and find a way to fix it - fill free to make a PR, I will review it.

There might be another, more simple way to fix - changing the [SDK/NDK lookup algorithm](https://github.com/JetBrains/skiko/blob/c479fc9b52497c2b33ff4b20612ad801178086e1/skiko/buildSrc/src/main/kotlin/tasks/configuration/JvmTasksConfiguration.kt#L137). Currently it is very specific - it doesn't use AGP for publication, it uses utilities directly. It might be the reason that something is wrong, and we need to convert publishing to using AGP.

**Comment by okushnikov** [comment] 2024-09-25 09:49
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-761">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-25 10:37 UTC
Labels: bug, android
